# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('nueva', models.BooleanField(verbose_name='Nueva')),
                ('agregada', models.DateTimeField(auto_now_add=True)),
                ('modificada', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='notice_image')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bandana',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Categoria', verbose_name='Categor\xeda'),
        ),
    ]
