# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_bandana_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandana',
            name='precio',
        ),
        migrations.AddField(
            model_name='categoria',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
